name: OverseerMain
author: AndyAndreiH
authors: [Migs84]
website: http://katgamestudios.com/
main: com.katgamestudios.andyandreih.overseer.main.OverseerMain
version: 0.0.4-SNAPSHOT
depend: [SQLibrary]
loadbefore: [OverseerAuth]
database: false
commands:
   overseer:
      description: The main command for Overseer
      usage: /overseer [subcommand/help]
      aliases: os
permissions:
   overseer.*:
      description: Master permission node